<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\project\ork\Ork.Clients\Ork.Clients.csproj" />
    <ProjectReference Include="..\..\..\..\project\ork\Ork.Models\Ork.Models.csproj" />
    <ProjectReference Include="..\Tide.Asgard.AspNetCore.DPoP\Tide.Asgard.AspNetCore.DPoP.csproj" />
    <ProjectReference Include="..\Tide.Asgard.AspNetCore\Tide.Asgard.AspNetCore.Authentication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\tide_dpop_auth.html" />
  </ItemGroup>

  <ItemGroup>
    <None Update="client.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
